baseURL = "https://nullbadgers.github.io/hugo_testing/"
languageCode = "en-us"
title = "Hugo testing by nullBadgers"
theme = "PaperMod"

[params]
  author = "nullBadgers"
  description = "A simple blog built with Hugo and PaperMod"
  mainSections = ["posts"]
  hideCopyright = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = true


[params.homeInfoParams]
title = "Hello explorer!"
content = "Welcome to my WIP blog"

[params.footer]
  text = "© 2025 nullBadgers • All rights reserved"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5