baseURL = "https://nullbadgers.github.io/hugo_testing/"
languageCode = "en-us"
title = "Hugo testing"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "nullBadgers"
  description = "A simple blog built with Hugo and PaperMod"
  mainSections = ["posts"]
  hideCopyright = false
  ShowReadingTime = true
  ShowPostNavLinks = true

[params.footer]
  text = "© 2025 nullBadgers • All rights reserved"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3