baseURL = "https://nullbadgers.github.io/hugo_testing/"
languageCode = "en-us"
title = "Hugo blog testing"
theme = "ananke"

[params]
  author = "nullBadgers"
  description = "A simple blog built with Hugo and Ananke"
  featured_image = "/images/hero.jpg"
  footer = "© 2025 nullBadgers"
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3